server:
  port: 8082  # microservice Property tourne sur le port 8082

spring:
  application:
      name: listing-service
  datasource:
    url: jdbc:mysql://localhost:4306/rental_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Crée auto les tables si elles n’existent pas.Met à jour le schéma si les entités sont modifiees ,Ne supprime pas les données.
    show-sql: true       # Affiche les requêtes SQL dans la console
    properties:
      hibernate:
        format_sql: true

  # Pour éviter les problèmes de redémarrage avec DevTools
  devtools:
    restart:
      enabled: true