global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - api-gateway:8080
          - user-service:8081
          - listing-service:8082
          - booking-service:8083
          - payment-service:8084
          - messaging-service:8085
          - notification-service:8086
          - review-service:8087
          - media-service:8088
          - blockchain-service:8089
          - ai-service:8090
