apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  MYSQL_HOST: real-estate-dapp-db-dev.cnwseskwiq1u.eu-west-3.rds.amazonaws.com
  MYSQL_PORT: "3306"
  MYSQL_DB: rental_db
  MYSQL_URL: jdbc:mysql://real-estate-dapp-db-dev.cnwseskwiq1u.eu-west-3.rds.amazonaws.com:3306/rental_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  MYSQL_USER: admin

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"

  EUREKA_HOST: eureka-server
  EUREKA_PORT: "8761"
  EUREKA_URL: http://admin:admin123@eureka-server:8761/eureka/

  AWS_REGION: eu-west-3
  S3_PROPERTIES_BUCKET: real-estate-dapp-properties-images-dev
  S3_USERS_BUCKET: real-estate-dapp-users-photos-dev
  CLOUDFRONT_URL: https://d32xfdels11cfk.cloudfront.net

  USER_SERVICE_PORT: "8081"
  LISTING_SERVICE_PORT: "8082"
  BOOKING_SERVICE_PORT: "8083"
  PAYMENT_SERVICE_PORT: "8084"
  MESSAGING_SERVICE_PORT: "8085"
  NOTIFICATION_SERVICE_PORT: "8086"
  MEDIA_SERVICE_PORT: "8087"
  REVIEW_SERVICE_PORT: "8088"
  BLOCKCHAIN_SERVICE_PORT: "8089"
  AI_SERVICE_PORT: "8090"
  API_GATEWAY_PORT: "8080"

  APP_MODE: production
  CORS_ALLOWED_ORIGINS: http://real-estate-dapp-alb-dev-2096892691.eu-west-3.elb.amazonaws.com
