apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
type: Opaque

stringData:
  MYSQL_USER: admin
  MYSQL_PASSWORD: db_password_dev_1234
  MYSQL_ROOT_PASSWORD: db_password_dev_1234

  RABBITMQ_USER: guest
  RABBITMQ_PASS: guest

  EUREKA_ADMIN_USER: admin
  EUREKA_ADMIN_PASS: admin123

  ADMIN_PRIVATE_KEY: 95f943fbd16b6288242988cc02a48e9519fe37a71f989bde1687e7c471ea214f
  WALLET_ENCRYPTION_KEY: 7e4d9c12cfb1a7e08e583d0a9fc4b8d298c44cc7d3ef0fa1c29f35d59a046be3
  GAS_PRICE: "20000000000"
  GAS_LIMIT: "500000"

#  MAIL_USERNAME: "ton.adresse@gmail.com"
  MAIL_USERNAME: "fatimaezzahraallai4@gmail.com"
  MAIL_PASSWORD: xxx
  INFURA_PROJECT_ID: 50e3d616c7ae4bb4bb5d48d97ab6d5a8

  TWILIO_ACCOUNT_SID: ACb40aaed57bd1f5f08d89b1b912559b78
  TWILIO_AUTH_TOKEN: 09d28f38519895c26ad9e1d5610f9230
  TWILIO_PHONE_NUMBER: "+12673148246"

  JWT_SECRET: password321
