# Configuration du serveur
server:
  port: ${EUREKA_PORT:8761}

# Configuration Spring
spring:
  application:
    name: eureka-server

# Configuration Eureka Server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://admin:admin123@eureka-server:8761/eureka/}

  server:
    eviction-interval-timer-in-ms: 10000
    enable-self-preservation: false
    renewal-percent-threshold: 0.85
    response-cache-update-interval-ms: 5000

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    com.rental.eurekaserver: DEBUG

# Security Admin (via variables d'environnement)
security:
  user:
    name: ${EUREKA_ADMIN_USER:admin}
    password: ${EUREKA_ADMIN_PASS:admin123}
